# Generated by Django 3.2.4 on 2021-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='c89b1', max_length=30),
        ),
    ]
