# Generated by Django 3.2.4 on 2021-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_course_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='9a72e', max_length=30),
        ),
    ]
