# Generated by Django 3.2.4 on 2021-07-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_choice_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='teacher.question'),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(default='Untitled Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(default='Untitled Form', max_length=30),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher.form'),
        ),
    ]
