# Generated by Django 3.2.4 on 2021-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='interested_students', to='accounts.Course'),
        ),
    ]
