# Generated by Django 3.2.4 on 2021-07-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210706_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
