# Generated by Django 3.2.4 on 2021-07-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_alter_course_subject'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joincourse',
            name='student',
        ),
        migrations.AlterField(
            model_name='joincourse',
            name='courses',
            field=models.ManyToManyField(to='teacher.Course'),
        ),
    ]
