# Generated by Django 3.2.4 on 2021-07-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210705_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinCourse',
        ),
    ]
