# Generated by Django 3.2.4 on 2021-07-05 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210706_0144'),
        ('teacher', '0016_alter_course_subject'),
        ('student', '0003_delete_joincourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('studentID', models.IntegerField(null=True, unique=True)),
                ('course', models.ManyToManyField(to='teacher.Course')),
            ],
        ),
    ]
