# Generated by Django 3.2.4 on 2021-08-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_auto_20210723_1213'),
        ('student', '0007_alter_answer_givenanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='givenAnswer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.choice'),
        ),
    ]
