# Generated by Django 3.2.4 on 2021-08-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_auto_20210723_1213'),
        ('student', '0008_alter_answer_givenanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.form'),
        ),
    ]
