# Generated by Django 3.2.4 on 2021-08-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_studentwindowdetectionlog_totalseconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentwindowdetectionlog',
            name='totalSeconds',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
