# Generated by Django 3.2.4 on 2021-08-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentwindowdetectionlog_totalseconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwindowdetectionlog',
            name='totalSeconds',
            field=models.IntegerField(null=True),
        ),
    ]
